controllers:
    resource: ../../src/Controller/
    type: annotation
#web_controller:
#    resource: ../../src/Controller/
#    type: annotation
rest_controller:
    resource: ../../src/Controller/Rest/
    type: annotation
    prefix: /api